- title: Your Website
  description: I build your Website, whether its a personal blog or your businesses online presence.
  icon: '<i class="fas text-white text-xl fa-globe-americas"></i>'

- title: Agile Coaching
  description: I join your team and help you adopting useful agile practices.
  icon: '<i class="fas text-white text-xl fa-flag-checkered"></i>'

- title: App Development
  description: I make your product idea real, whether its a webapp or a native app.
  icon: '<i class="fas text-white text-xl fa-rocket"></i>'

- title: Blogging
  description: I blog about software engineering, agile practices and quality assurance.
  icon: '<i class="fas text-white text-xl fa-newspaper"></i>'
